# Generated by Django 5.0.4 on 2024-04-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_buynow2_order_cartitem_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banner_images/')),
            ],
        ),
    ]
