# Generated by Django 5.0.4 on 2024-04-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_food_banner_1_food_banner_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_banner_1',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='food_banner_2',
            name='text',
            field=models.TextField(),
        ),
    ]
