# Generated by Django 5.0.4 on 2024-04-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_food_banner_1_text_alter_food_banner_2_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='food_banner_1',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='food_banner_2',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
    ]
