# Generated by Django 5.0.4 on 2024-04-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_banner_price_food_banner_1_price_food_banner_2_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buynow2',
            name='product_brand',
        ),
        migrations.RemoveField(
            model_name='buynow2',
            name='product_category',
        ),
    ]
