# Generated by Django 5.0.4 on 2024-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_buynow2_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow2',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
