# Generated by Django 5.0.4 on 2024-04-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_remove_grocery_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='rating',
        ),
    ]
