# Generated by Django 5.0.4 on 2024-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_remove_grocery_rating_remove_menuitem_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='image',
            new_name='image_main',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='image',
            new_name='image_main',
        ),
        migrations.AddField(
            model_name='grocery',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='grocery_item_images/'),
        ),
        migrations.AddField(
            model_name='grocery',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='grocery_item_images/'),
        ),
        migrations.AddField(
            model_name='grocery',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='grocery_item_images/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='menu_item_images/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='menu_item_images/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='menu_item_images/'),
        ),
    ]
