# Generated by Django 5.0.4 on 2024-04-12 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_rename_image_grocery_image_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
