# Generated by Django 5.0.4 on 2024-04-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_grocery_item_id_menuitem_item_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
