# Generated by Django 5.0.4 on 2024-04-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
