# Generated by Django 5.0.4 on 2024-04-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='product_type',
            field=models.CharField(default='Grocery', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='product_type',
            field=models.CharField(default='MenuItem', editable=False, max_length=10),
        ),
    ]
